### ISSUE TITLE
Error using with Windows. "Error: Could not initialize PortAudio: Internal PortAudio error"

### ISSUE THREAD

**Issue by matheusfenolio** [Streampunk/naudiodon#48]
I tried to use naudiodon in my Node project. It worked in my Ubuntu, but in Windows I'm receiving an error. I tried to reinstall all packages, but still the same. I'm not sure what's wrong. Follow some prints. 

![image](https://user-images.githubusercontent.com/37229507/86502479-f9ed6a80-bd79-11ea-8742-5ccbd8a758ee.png)

![image](https://user-images.githubusercontent.com/37229507/86502485-070a5980-bd7a-11ea-9109-49a00a70545f.png)

![image](https://user-images.githubusercontent.com/37229507/86502489-1b4e5680-bd7a-11ea-984d-68e1b199ebe7.png)

![image](https://user-images.githubusercontent.com/37229507/86502494-2a350900-bd7a-11ea-87f0-7673a23decd5.png)

**Comment by scriptorian** [comment]
I'm sorry that you are having trouble with this. I've updated everything and rebuilt and can't reproduce the problem on my machine. As you have noted, the problem lies with initialising portaudio, but there is no information to explain what has gone wrong. My only thought of something to try at the moment would be to look at the list of applications on the portaudio website and see if any of them give more clues as to what is going on.

**Comment by matheusfenolio** [comment]
Thanks for response. I'll it again with a VM for test in a fresh Windows installation. When a have some new I'll come back here.

**Comment by matheusfenolio** [comment]
It wasn't a naudiodon issue. I tried in a new VM and it worked. I don't know what`s wrong yet.

**Comment by matheusfenolio** [comment]
It wasn't a naudiodon issue. I tried in a new VM and it worked. I don't know what`s wrong yet.

**Comment by matheusfenolio** [comment]
I came back to the project and tried the solution proposed on issue #42 and now it works.
